---
- name: Enable cockpit socket
  ansible.builtin.systemd:
    name: cockpit.socket
    state: started
    enabled: yes

- name: Permit traffic in default zone for cockpit
  firewalld:
    service: cockpit
    permanent: yes
    immediate: yes
    state: enabled
