all:
  hosts:
  children:
    local:
      hosts:
        rhel-kvm:
          ansible_connection: local
    ipaserver:
      hosts:
        rhel-kvm.homelab.cedricanderson.name:
          ansible_connection: local
          ipaserver_domain: homelab.cedricanderson.name
          ipaserver_realm: HOMELAB.CEDRICANDERSON.NAME
          ipaserver_setup_dns: yes
          ipaserver_auto_forwarders: yes
          ipaserver_allow_zone_overlap: yes
          ipaadmin_password: MySecretPassword123
          ipadm_password: MySecretPassword234
