all:
  hosts:
  children:
    rhvserver:
      hosts:
        rhel:
          ansible_connection: local
    ipaserver:
      hosts:
        rhel.lab.cedricanderson.name:
          ansible_connection: local
          ipaserver_domain: lab.cedricanderson.name
          ipaserver_realm: LAB.CEDRICANDERSON.NAME
          ipaserver_setup_dns: yes
          ipaserver_auto_forwarders: yes
          ipaserver_allow_zone_overlap: yes
          ipaadmin_password: MySecretPassword123
          ipadm_password: MySecretPassword234
